# Generated by Django 4.1.4 on 2023-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='clothes',
            field=models.ManyToManyField(to='catalog.clothes'),
        ),
    ]
