# Generated by Django 4.1.4 on 2023-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_orders_clothes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
