# Generated by Django 4.1.4 on 2023-01-18 18:14

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_users_name_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('adress'), descending=True), models.F('name'), name='lower_adress_name_idx'),
        ),
    ]
