# Generated by Django 4.1.4 on 2023-01-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_users_lower_adress_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('adress', models.CharField(max_length=50, verbose_name='адрес')),
                ('discont_card', models.IntegerField(verbose_name='скидка')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery_orders',
            fields=[
                ('orders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.orders')),
                ('adress', models.CharField(max_length=100, verbose_name='aдрес доставки')),
                ('name', models.IntegerField(verbose_name='покупатель')),
                ('comment', models.TextField(verbose_name='комментарий к заказу')),
            ],
            bases=('catalog.orders',),
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('adress', models.CharField(max_length=50, verbose_name='адрес')),
                ('experiences', models.IntegerField(verbose_name='стаж')),
                ('level_access', models.IntegerField(verbose_name='уровень допуска')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Take_away_orders',
            fields=[
                ('orders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.orders')),
                ('comment', models.TextField(verbose_name='комментарий к заказу')),
            ],
            bases=('catalog.orders',),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
