# Generated by Django 4.1.4 on 2023-01-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_costumers_delivery_orders_managers_take_away_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Одежда'},
        ),
        migrations.RemoveField(
            model_name='delivery_orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shop',
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.IntegerField(default=1, verbose_name='категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumers',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.orders'),
        ),
        migrations.AddField(
            model_name='shop',
            name='managers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.managers'),
        ),
        migrations.AddField(
            model_name='shop',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.orders'),
        ),
    ]
