# Generated by Django 4.1.4 on 2023-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_costumers_balance_shop_balance_alter_article_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.IntegerField(null=True, verbose_name='категория'),
        ),
    ]
