name: django-shop
on: workflow_dispatch
jobs:
  copy_data:
    runs-on: ubuntu-latest
    steps:
      - name: Copy data
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependences
        run: pip install -r requirements.txt
        
  information:
    runs-on: ubuntu-latest
    needs: copy_data
    steps:
    - name: info about job informations
      run: |
        echo info 1
        echo info 2
        echo info 3
     
 

