name: django-shop
on: workflow_dispatch
jobs:
  copy_data:
    runs-on: ubuntu-latest
    steps:
      - name: Copy data
      - uses: actions/checkout@v3
      - name: End copy
        run: echo finish copy

