name: django-shop
on: workflow_dispatch
jobs:
  copy_data:
    runs-on: ubuntu-latest
    steps:
      - name: Copy data
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
 

