name: Django CI
on: workflow_dispatch

jobs:
  output:
#     strategy:
#       matrix:
#         python-version: [3.8,3.9,3.10]    
    runs-on: ubuntu-latest
    steps:
      - name: Create repository cod
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
#         with:
#           python-version: ${{matrix.python-version}}
      - name: Install dependences
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
          
       
