name: Django CI
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository cod
        uses: actions/checkout@v3
      - name: Install python 
        uses: actions/setup-python@v3
      - name: Install dependences
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
          
       
